enum AnimationAttribute {
  id = 'id ',
  class = 'class ',
  style = 'style ',
  begin = 'begin',
  dur = 'dur',
  end = 'end',
  min = 'min ',
  max = 'max ',
  restart = 'restart ',
  repeatCount = 'repeatCount ',
  repeatDur = 'repeatDur ',
  fill = 'fill ',
  calcMode = 'calcMode ',
  values = 'values ',
  keyTimes = 'keyTimes ',
  keySplines = 'keySplines ',
  from = 'from ',
  to = 'to ',
  by = 'by ',
  attributeName = 'attributeName ',
  additive = 'additive ',
  accumulate = 'accumulate ',
}

export default AnimationAttribute
